[workspace]
members = [
    "program",
    "script",
]
resolver = "2"

[workspace.dependencies]
alloy-sol-types = "0.7.7"

[profile.release]
codegen-units = 1
lto = "fat"
strip = "symbols"
panic = "abort"