[package]
version = "0.1.0"
name = "fuel-vm-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = "4.1.7"
fuel-vm-lib = { path = "../../lib" }

[profile.release]
codegen-units = 1
lto = "fat"
strip = "symbols"
panic = "abort"